#Config Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityDb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: pass_
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

#JWT
jwt:
  secret:
    key: nLKq7m2AXfLKRncYsqXtCKpBvrfyUMngxGg3LfIDZ4NenKXGSEpzmOnnqTtWf3mt
  time:
    expiration: 86400000
