# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: yt-mongo
    hostname: host-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb
