# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: yt-mongo
    hostname: host-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./data/mongodb:/data/db
      - ./data/mongodb/log:/var/log/mongodb
  mysql:
    container_name: yt-mysql
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    hostname: host-mysql
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass_'
      MYSQL_ROOT_PASSWORD: 'pass_root'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: 'rabbitmq'
    hostname: host-rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/log/:/var/log/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: yt-keycloak
    hostname: host-keycloak
    ports:
    - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev